version: '3.4'

services:
  clean-arch-app:
    image: clean-arch-app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/main/server.js